### PR TITLE
Milestone 2

### PR DESCRIPTION
**Pull request by Tresor11**

### CODE REVIEW

**Comment by WCanirinka** [comment]
Requesting for a review for the user_interface

**Review by Redvanisation — APPROVED** [review]
## In review...

**Review by Redvanisation — CHANGES_REQUESTED** [review]
# Changes required  ♻️ 

### Hello team  🌟

**Good work on this project, but we need to fix the issues below before moving on ⬇️** 

1. The milestone isn't completed you need to implement the following: 

* [x] `[REQUIRED]` game asks player to select from available moves
* [x] `[REQUIRED]` game informs player if selected move is invalid
* [x] `[REQUIRED]` game displays board after player move
* [x] `[REQUIRED]` game informs player if selected move is a winning move
* [x] `[REQUIRED]` game informs player if selected move is a draw move
* [x] `[REQUIRED]` game repeats all actions for next player's move

2. Make the game logic, players should be able to do the functionality stated above on each turn.

3. Update the name of the `main` file to `main.rb`.

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

**Comment by Tresor11** [comment]
we have made the changes and we are requesting for another review

**Review by wathigo — APPROVED** [review]
# Approved :smile: 
## Great work implementing the user interface :clap: 
### You may move on :next_track_button: 

**Happy Coding :computer: 
Simon Wathigo**

**Pull request merged**
